#!/bin/zsh

# Алиасы
alias c="clear"
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gs="git status"
alias gclean="git clean -fd; git checkout ."
alias dd="composer dump-autoload"
alias q="phpunit --testdox"
alias qq="composer test"
